### ISSUE TITLE
Bundle components properly for tree-shaking.

### ISSUE THREAD

**Issue by Utwo** [code4romania/taskforce-fe-components#180]
In the current version this component library together with all the dependencies (echarts, react-datepicker, uderscore, date-fns) is not tree-shakable. So every consumer app that is importing a single button from this library will end up with all the components and dependencies from **fe-components** in consumer app bundle.

In diaspora-hub and ce-ma-fac application, the bundle looks something like this. Even though they don't use components with echarts or datepicker, we can see that they are included in final build and loaded on every request. 

**ce-ma-fac**
![image1](https://user-images.githubusercontent.com/282668/80514510-48047d00-8989-11ea-8412-f5b6f6764bae.png)

**diaspora-hub**
![image](https://user-images.githubusercontent.com/282668/80514514-4935aa00-8989-11ea-884e-f1e70368de79.png)

**Comment by tudorgergely** [comment]
I think we should bundle the components separately so you can import them directly (e.g. `import Button from 'taskforce-fe-components/Button'`).

If we do it this way we can also import the css the same way  `import 'taskforce-fe-components/Button.css'`.

This will require a change in the respective projects but will work better compared to letting the bundler decide what to tree shake (also not possible sometimes because of 3rd party libraries). We can also keep the existing imports as well so we don't break existing apps using them.

What do you think @Utwo ?
